### ISSUE TITLE
Release 1.6.6 breaks backward compatibility with existing FHIR types

### ISSUE THREAD

**Issue by yinzara** [Vermonster/fhir-kit-client#155] opened 2021-08-20 22:57 UTC
Release 1.6.6 of the library introduced the built in TypeScript types that are completely different than the @types/fhir-kit-client published previously breaking all backwards compatibility and since the embedded types are preferred by TypeScript there's no way to use the old types library with version 1.6.6+.

This should not have been an incremental release of the library. It should have at least been minor, if not major release (i.e. it should have been 2.0.0 or at least 1.7.0) as it's a major change to how you use the library and requires users to change their codebase.  I do understand those types were not published by the library maintainers, however that doesn't change the fact that they were published and there's an issue with library compatibility which should never happen in incremental versions.  Swapping from DefinitelyTyped types to types included in the library are a big change.

Because of this all automated upgrade tools keep trying to upgrade fhir-kit-client to the latest incremental release breaking code everywhere.

Unfortunately, the only way to really fix this is to put out a 1.6.9 release that's actually a duplicate of the 1.6.5 release then put out a 1.7.0 or 2.0.0 with the latest code.

Additionally I see that the @types/fhir-kit-client was also updated to reflect these changes.  If the types are moved to be included with the library, they should be removed from DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#removing-a-package

**Comment by bkaney** [comment] 2021-08-21 12:28
> Unfortunately, the only way to really fix this is to put out a 1.6.9 release that's actually a duplicate of the 1.6.5 release then put out a 1.7.0 or 2.0.0 with the latest code.

Okay, we can do the following to `fhir-kit-client`:
1. Make version 1.6.9 that is a duplicate of 1.6.5 (without types)
2. Make version 1.7.0 that will be the current release (with types)

For `@types/fhir-kit-client` either :
* keep the @types/fhir-kit-client as is; or
* change these https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fhir-kit-client/index.d.ts#L12-L14 to be back to R3 for anyone using it with fhir-kit-client (maybe update the header version, it is currently 1.1); or
* Delete it from DT.
 
What do you think?

**Comment by yinzara** [comment] 2021-09-05 05:02
Yeah I'd say change the @types/fhir-kit-client back to the R3 types to match the new version you're releasing and change it's version to 1.6.9 so it matches the 1.6.9 release

Then you can run the command in DefinitelyTypes to retire the types and make it version 1.7.0 (which will cause the message "this is a stub type definition" if anyone tries to add it).

**Comment by bkaney** [comment] 2021-09-30 01:08
Done the part here. Will try to address the DT side later. See https://www.npmjs.com/package/fhir-kit-client/v/1.6.9

**Closed** 2022-03-07 16:15 UTC
