### ISSUE TITLE
It should work on Angular

### ISSUE THREAD

**Issue by StephanMeijer** [Vermonster/fhir-kit-client#92] opened 2019-03-12 16:26 UTC
## Expected Behavior
It should work on Angular

## Actual Behavior
It fails resolving native nodejs libraries

```
[npm] ERROR in ./node_modules/aws-sign2/index.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/aws-sign2'
[npm] ERROR in ./node_modules/aws4/aws4.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/aws4'
[npm] ERROR in ./node_modules/ecc-jsbn/index.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/ecc-jsbn'
[npm] ERROR in ./node_modules/http-signature/lib/verify.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/http-signature/lib'
[npm] ERROR in ./node_modules/http-signature/lib/signer.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/http-signature/lib'
[npm] ERROR in ./node_modules/oauth-sign/index.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/oauth-sign'
[npm] ERROR in ./node_modules/request/lib/helpers.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/request/lib'
[npm] ERROR in ./node_modules/request/lib/oauth.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/request/lib'
[npm] ERROR in ./node_modules/request/lib/hawk.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/request/lib'
[npm] ERROR in ./node_modules/sshpk/lib/utils.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/fingerprint.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/identity.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/private-key.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/signature.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/certificate.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/key.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/dhe.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/Uapp/node_modules/sshpk/lib/formats'
[npm] ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib/formats'
[npm] ERROR in ./node_modules/sshpk/lib/formats/pem.js
[npm] Module not found: Error: Can't resolve 'crypto' in '/app/node_modules/sshpk/lib/formats'
[npm] ERROR in ./node_modules/request/lib/har.js
[npm] Module not found: Error: Can't resolve 'fs' in '/app/node_modules/request/lib'
[npm] ERROR in ./node_modules/forever-agent/index.js
[npm] Module not found: Error: Can't resolve 'http' in '/app/node_modules/forever-agent'
[npm] ERROR in ./node_modules/http-signature/lib/signer.js
[npm] Module not found: Error: Can't resolve 'http' in '/app/node_modules/http-signature/lib'
[npm] ERROR in ./node_modules/request/request.js
[npm] Module not found: Error: Can't resolve 'http' in '/app/node_modules/request'
[npm] ERROR in ./node_modules/tunnel-agent/index.js
[npm] Module not found: Error: Can't resolve 'http' in '/app/node_modules/tunnel-agent'
[npm] ERROR in ./node_modules/forever-agent/index.js
[npm] Module not found: Error: Can't resolve 'https' in '/app/node_modules/forever-agent'
[npm] ERROR in ./node_modules/request/request.js
[npm] Module not found: Error: Can't resolve 'https' in '/app/node_modules/request'
[npm] ERROR in ./node_modules/tunnel-agent/index.js
[npm] Module not found: Error: Can't resolve 'https' in '/app/node_modules/tunnel-agent'
[npm] ERROR in ./node_modules/forever-agent/index.js
[npm] Module not found: Error: Can't resolve 'net' in '/app/node_modules/forever-agent'
[npm] ERROR in ./node_modules/tough-cookie/lib/cookie.js
[npm] Module not found: Error: Can't resolve 'net' in '/app/node_modules/tough-cookie/lib'
[npm] ERROR in ./node_modules/tunnel-agent/index.js
[npm] Module not found: Error: Can't resolve 'net' in '/app/node_modules/tunnel-agent'
[npm] ERROR in ./node_modules/mime-types/index.js
[npm] Module not found: Error: Can't resolve 'path' in '/app/node_modules/mime-types'
[npm] ERROR in ./node_modules/assert-plus/assert.js
[npm] Module not found: Error: Can't resolve 'stream' in '/app/node_modules/assert-plus'
[npm] ERROR in ./node_modules/combined-stream/lib/combined_stream.js
[npm] Module not found: Error: Can't resolve 'stream' in '/app/node_modules/combined-stream/lib'
[npm] ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
[npm] Module not found: Error: Can't resolve 'stream' in '/app/node_modules/delayed-stream/lib'
[npm] ERROR in ./node_modules/isstream/isstream.js
[npm] Module not found: Error: Can't resolve 'stream' in '/app/node_modules/isstream'
[npm] ERROR in ./node_modules/request/request.js
[npm] Module not found: Error: Can't resolve 'stream' in 'app/node_modules/request'
[npm] ERROR in ./node_modules/sshpk/lib/ed-compat.js
[npm] Module not found: Error: Can't resolve 'stream' in '/app/node_modules/sshpk/lib'
[npm] ERROR in ./node_modules/forever-agent/index.js
[npm] Module not found: Error: Can't resolve 'tls' in '/app/node_modules/forever-agent'
[npm] ERROR in ./node_modules/tunnel-agent/index.js
[npm] Module not found: Error: Can't resolve 'tls' in '/app/node_modules/tunnel-agent'
[npm] ERROR in ./node_modules/request/request.js
[npm] Module not found: Error: Can't resolve 'zlib' in '/app/node_modules/request'
```

## Steps to Reproduce the Problem

  1. Install and use on Ionic/Angular

## Specifications

  - Version: Latest
  - Platform: Ionic, Angular
  - Subsystem: Mac

**Comment by bkaney** [comment] 2019-03-12 16:32
Hmm, we will have to try a simple “hello world” Angular app to try to reproduce this... 

Do you happen to have one pushed up to a public repo that demonstrates this problem?

**Comment by bkaney** [comment] 2019-03-16 18:12
I think this is a dupe of #93. See the comments there.

**Closed** 2019-03-16 18:26 UTC
