### ISSUE TITLE
Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by yunwwang** [Vermonster/fhir-kit-client#93] opened 2019-03-15 18:38 UTC
## Expected Behavior
Angular 6 app launches without error

## Actual Behavior
Angular 6 app launches with "Can't resolve 'crypto'" error

## Steps to Reproduce the Problem

  1. Create an angular 6 app
  2. install fhir-kit-client using npm
  3. import fhir-kit-client to component
  4. add code to noOnInit()
`
    public ngOnInit(): void {
        const Client = require('fhir-kit-client');
        const iss = this._route.snapshot.queryParams['iss'];

        const fhirClient = new Client({baseUrl: iss});
        ...
    }
`
  5. start the app using "ng serve"

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by bkaney** [comment] 2019-03-16 18:11
This seems to be a bug in Angular (see: https://blog.lysender.com/2018/07/angular-6-cannot-resolve-crypto-fs-net-path-stream-when-building-angular/) -- can you see if this fixes it. This also seems like a dupe of #92.

Can you confirm the workarounds here work for you?

Also see:
* https://github.com/angular/angular-cli/issues/1548
* https://stackoverflow.com/questions/51087330/angular-6-many-cant-resolve-errors-crypto-fs-http-https-net-path-stream

**Comment by froid1911** [comment] 2019-03-26 07:01
you are closing #93 because of dupe of #92
and you are closing #92 because of dupe of #93

**Comment by bkaney** [comment] 2019-03-26 11:36
Hi @froid1911 — #93 (this one) is currently open? Not sure what you mean by your comment...

In all likelihood we will include instructions on how to adjust the webpack configuration for Angular 6 per the links above. What are your thoughts?

**Comment by froid1911** [comment] 2019-03-28 09:54
opsi, thought it got closed. sry for that :-) ........

**Comment by yunwwang** [comment] 2019-04-19 20:45
Worked whole afternoon trying to get angular 6 project working. Tried using @angular-builders/custom-webpack. Now ng build works but ng serve still not working. If anyone have a successful angular 6 project using this client js, please let me know.

**Comment by bkaney** [comment] 2019-04-19 22:49
I looked at this a bit today. To make requests work on the server for node apps, we use `request`, (which depends on the `crypto` library, not avail in the browser). For the browser, we use `request-promise-native`. However, `request-promise-native` has a peer dependency of `request`. Angular doesn't like this even though the polyfill never actually loads the one requiring crypto.

**Comment by foxtree** [comment] 2019-04-26 18:18
> but ng serve still not working. 

@yunwwang 

I tried following the guide, here, and it seems to work with Angular-7:
https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21
(^This guide mentions Angular-6 -- if for any reason this does _not_ work with 6, try upgrading to Angular 7?) 

*  You would have to `npm i -D` (or, `yarn add -D`) `@angular-builders/dev-server`

* The following changes to `angular.json` seemed to enable `ng serve` to work with `fhir-kit-client`:

![image](https://user-images.githubusercontent.com/3383704/56827828-dea9d580-682d-11e9-8aa2-cd42ffb21fcf.png)

**Comment by yunwwang** [comment] 2019-05-03 15:26
@foxtree Do you mind to create a sample codes for Anguar 6/7? That would be really helpful.

**Comment by bkaney** [comment] 2019-07-31 21:11
This should be resolved in 1.4.0 now. Also check out the examples here: https://github.com/Vermonster/fhir-kit-client-examples

**Closed by bkaney** 2019-07-31 21:11 UTC
